name: run-tests
on:
  pull_request:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install dependencies
        uses: borales/actions-yarn@v5
        with:
          cmd: install --frozen-lockfile

      - name: Run tests manually?
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"
        run: |
          echo $(pwd)
          echo $(ls)
          cd packages/faro-webpack
          yarn test
          cd ../faro-rollup
          yarn test

      - name: Run tests
        uses: borales/actions-yarn@v5
        with:
          cmd: test

      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: build
