name: run-tests
on:
  pull_request:

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: $BRANCH_NAME

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
